### ISSUE TITLE
SassMagic

### ISSUE THREAD

**Issue by airen** [Famolus/awesome-scss#12]
SassMagic is a collection of Sass mixins and functions to ease and improve our implementations of common style-code patterns.

Collection best of Sass Mixins and Function.If you have seen good and meaningful Mixins or Functions, please send us your code.Let more students share your results.

https://github.com/w3cplus/SassMagic

More Chinese tutorials：http://www.w3cplus.com/blog/tags/302.html

**Comment by tandavas** [comment]
Move the conversation to #20
