### ISSUE TITLE
Add "shevy" for vertical rhythms

### ISSUE THREAD

**Issue by vwochnik** [Famolus/awesome-scss#15]
[Shevy][1] (kyleshevlin/shevy) is really good. I am using it for three websites now. 

[1]: https://github.com/kyleshevlin/shevy

**Comment by tandavas** [comment]
I think we will pass with this one. It would be really nice if it got examples and demo for people to see. That would help a lot.

**Comment by vwochnik** [comment]
I have talked to the author and due to your suggestions he has created a new website containing a documentation and examples. Therefore, I'd like you to add this library to the list.

**Comment by tandavas** [comment]
Cool! Would you mind sending a pull request for this?
