### ISSUE TITLE
Create categories for 'Libraries and Mixins'

### ISSUE THREAD

**Issue by hiulit** [Famolus/awesome-scss#5]
Right now this list is a bit of a chaos :P

We could try to split those links into categories.

Some examples:

* Color management
* Typography
* Media queries
* Etc.

**Comment by tandavas** [comment]
That's a great suggestion! 

Would you like to make a pull request for this?

**Comment by tandavas** [comment]
Thank you so much @flexbox for working on this. You're awesome 🍻
